PYTHON ?= .venv/Scripts/python
ifeq ($(OS),)
PYTHON := .venv/bin/python
endif

START ?= 2018-01-01
END   ?= 2026-06-05

.PHONY: test backtest paper report data

test:
	$(PYTHON) -m pytest

data:
	$(PYTHON) -m services.data_downloader EURUSD GBPUSD --start $(START) --end $(END) \
	  --db data/market.sqlite --cache data/dukascopy

backtest:
	$(PYTHON) -m backtest.engine --db data/market.sqlite --start $(START) --end $(END) \
	  --label campaign_$(START)_$(END)

report:
	@echo "reports are generated by 'make backtest' into ./reports/"
	@ls reports 2>/dev/null || dir reports

paper:
	@echo "paper mode needs a running MT5 terminal (demo login)."
	@echo "see RUNBOOK.md 'Paper trading' for the bring-up procedure."
